import { Clock3, ExternalLink, MapPin, MessageCircle, Phone, ShieldCheck } from 'lucide-react'
import { SectionHeading } from '../components/SectionHeading'
import { assets } from '../lib/data/assets'
import { phoneDisplay, phoneUrl, whatsappUrl } from '../lib/data/site'

const showroomAddress = 'Jl. MH. Thamrin No.63, Sentul, Kec. Babakan Madang, Kabupaten Bogor, Jawa Barat 16810'
const mapUrl = 'https://maps.app.goo.gl/2WV6S1WLczVFiwwC6?g_st=ac'
const mapEmbed = 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3963.6380095451245!2d106.8578237!3d-6.567290599999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e69c7707f7f4193%3A0xa8b98647a74f9d36!2sHyundai%20AEON%20Sentul%20Official!5e0!3m2!1sid!2sid!4v1790739081162!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="strict-origin-when-cross-origin'

export function ContactSection() {
  return <section id="contact" className="bg-surface py-16 lg:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="Lokasi & Kontak Resmi" title="Showroom & Konsultasi" description="Fasilitas showroom 3S eksekutif dan unit test drive lengkap siap menyambut Anda." /><div className="grid overflow-hidden rounded-3xl border border-line bg-white lg:grid-cols-12" data-reveal><div className="flex flex-col justify-between p-6 lg:col-span-5 lg:p-9"><div><div className="mb-7 flex items-center gap-3"><img src={assets.dealerLogo} alt="Hyundai Logo" className="h-7 w-auto object-contain" /><span className="text-sm font-bold text-ink">PT Sinar Inti Primajaya Perkasa</span></div><div className="space-y-5"><div className="flex gap-3"><MapPin size={18} className="mt-0.5 shrink-0 text-secondary" /><div><p className="text-sm font-bold text-ink">Showroom Sentul Bogor</p><p className="mt-1 text-sm leading-relaxed text-muted">{showroomAddress}</p></div></div><div className="flex gap-3"><Clock3 size={18} className="mt-0.5 shrink-0 text-secondary" /><div><p className="text-sm font-bold text-ink">Jam Operasional</p><p className="mt-1 text-sm text-muted">Senin - Minggu: 08.30 - 19.00 WIB</p></div></div><div className="flex items-center gap-2 text-xs font-semibold text-emerald-600"><ShieldCheck size={16} /> Dealer Resmi Terakreditasi</div></div></div><div className="mt-10 flex flex-col gap-3"><a href={whatsappUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl bg-secondary px-4 py-3 text-sm font-bold text-white"><MessageCircle size={16} /> Buat Janji Temu</a><a href={phoneUrl} className="inline-flex items-center justify-center gap-2 rounded-xl border border-line px-4 py-3 text-sm font-bold text-ink"><Phone size={16} /> {phoneDisplay}</a></div></div><div className="relative min-h-[320px] overflow-hidden bg-slate-200 lg:col-span-7"><iframe title="Lokasi showroom Sentul Bogor" className="absolute inset-0 h-full w-full border-0 grayscale-[0.2]" loading="lazy" src={mapEmbed} /><a href={mapUrl} target="_blank" rel="noreferrer" className="absolute bottom-4 right-4 inline-flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-xs font-bold text-ink shadow-lg">Buka di Maps <ExternalLink size={14} /></a></div></div><div className="mt-8 flex flex-wrap items-center gap-x-3 gap-y-2 border-t border-line pt-6 text-xs text-muted"><ShieldCheck size={17} className="text-secondary" aria-hidden="true" /><span>Sales Consultant Resmi</span><span className="text-line">•</span><span>Deva Agriani - Sales Supervisor</span></div></div></section>
}
